### PR TITLE
http2: send only when necessary

### PR DESCRIPTION
**Pull request by jasnell**
Fixes: https://github.com/nodejs/http2/issues/153
cc @sebdeckers

##### Checklist

- [ ] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Comment by sebdeckers** [comment]
Thanks @jasnell 👍 I just kicked the tires on this patch and it definitely solves the idle memory leak issue as well as the CPU usage.

Still seeing a leak of ~8 kilobytes per request.

#### `server.js`
```js
const MSG = 'Hello, World!'
require('http2').createServer((request, response) => {
  response.end(MSG)
}).listen(8080)
```

#### client
```
h2load -n 100000 -t 4 -c 20 http://localhost:8080/
```

#### Results

Memory before: ~10 MB
Memory after: ~800 MB

**Comment by jasnell** [comment]
Yep. I'm working on tracking that down. :)

**Comment by sebdeckers** [comment]
(Btw, what tools are used to profile memory use of Node.js's C/CPP side? Couldn't find much documentation about this. Node Inspector wasn't giving me much insight here. Or maybe I just don't know how to use it properly and interpret the data.)

**Comment by jasnell** [comment]
I'm using valgrind for the memory leak debugging

**Comment by jasnell** [comment]
@sebdeckers ... give this another shot. Hopefully the memory leak is gone... though I did notice a couple others in various other bits of code that I'll be looking into later.

**Comment by sebdeckers** [comment]
@jasnell Nice cleanup, more readable.

However the above test shows roughly the same high level result: memory usage runs up from 10 MB to 785-795 MB after 100k requests. Maybe a tiny decrease but hard to tell from my inaccurate Activity Monitor measurement. Are you seeing different results?

FWIW Node Inspector continues to show very low memory usage (~6 MB) before and after the test. Haven't figured out Valgrind yet (but thanks for the tip!)

**Comment by jasnell** [comment]
Currently there is going to be a bit higher retained memory use because of the internal freelist pools. Instances of certain classes/structs are built up on demand and cached for reuse, trading performance for a higher memory footprint. Those cap out at a certain number of objects so the retained memory should reach a fixed level at some point.

**Comment by mcollina** [comment]
800MB seems a bit too much for caching data structures. Is that just the RSS?

**Comment by jasnell** [comment]
It may be. I've noted high RSS previously but hadn't tracked it down. There are lots of Buffer allocations happening which could account for it. It's definitely something we should investigate

**Comment by jasnell** [comment]
@sebdeckers @mcollina ... can I get a sign off on this PR so I can get it landed. It solves the immediate leak and cpu usage issues. I'll be investigating further but need to get this landed first.

**Comment by jasnell** [comment]
Btw, here's the valgrind memcheck report for the test/parallel/test-http2-windows-size test:

<details>

```
$ valgrind --leak-check=full ./node test/parallel/test-http2-window-size.js
==28747== Memcheck, a memory error detector
==28747== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==28747== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==28747== Command: ./node test/parallel/test-http2-window-size.js
==28747==
==28747== Warning: set address range perms: large range [0xc94d8f8b000, 0xc94f8f8c000) (noaccess)
(node:28747) ExperimentalWarning: The http2 module is an experimental API.
==28747== Warning: set address range perms: large range [0xc94d8f8b000, 0xc94f8f8b000) (noaccess)
==28747==
==28747== HEAP SUMMARY:
==28747==     in use at exit: 4,936,473 bytes in 115,320 blocks
==28747==   total heap usage: 273,626 allocs, 158,306 frees, 141,447,199 bytes allocated
==28747==
==28747== 40 bytes in 1 blocks are definitely lost in loss record 580 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x125D1C1: node::Environment::Start(int, char const* const*, int, char const* const*, bool) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x1275FD9: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x126FA1E: node::Start(int, char**) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x5D2C3F0: (below main) (libc-start.c:291)
==28747==
==28747== 40 bytes in 1 blocks are definitely lost in loss record 581 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x125D1FF: node::Environment::Start(int, char const* const*, int, char const* const*, bool) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x1275FD9: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x126FA1E: node::Start(int, char**) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x5D2C3F0: (below main) (libc-start.c:291)
==28747==
==28747== 40 bytes in 1 blocks are definitely lost in loss record 582 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x125D23A: node::Environment::Start(int, char const* const*, int, char const* const*, bool) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x1275FD9: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x126FA1E: node::Start(int, char**) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x5D2C3F0: (below main) (libc-start.c:291)
==28747==
==28747== 40 bytes in 1 blocks are definitely lost in loss record 583 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x125D271: node::Environment::Start(int, char const* const*, int, char const* const*, bool) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x1275FD9: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x126FA1E: node::Start(int, char**) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x5D2C3F0: (below main) (libc-start.c:291)
==28747==
==28747== 40 bytes in 1 blocks are definitely lost in loss record 584 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x1255F8E: node::cares_wrap::(anonymous namespace)::Initialize(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x1269658: node::Binding(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x887898: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90C5B9: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90CEFD: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0xC94D918437C: ???
==28747==    by 0xC94D934E912: ???
==28747==    by 0xC94D918579A: ???
==28747==    by 0xC94D9268766: ???
==28747==    by 0xC94D923AFFB: ???
==28747==    by 0xC94D9307A26: ???
==28747==
==28747== 96 bytes in 3 blocks are possibly lost in loss record 595 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x1287C64: node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12A5FEE: node::http2::Http2Session::OnDataChunk(node::http2::Nghttp2Stream*, node::http2::nghttp2_data_chunk_t*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12A52D4: node::http2::Nghttp2Session::OnFrameReceive(nghttp2_session*, nghttp2_frame const*, void*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x133493C: nghttp2_session_on_data_received (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x1338596: nghttp2_session_mem_recv (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12A8C34: node::http2::Http2Session::OnStreamReadImpl(long, uv_buf_t const*, uv_handle_type, void*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12E3F3D: node::StreamWrap::OnRead(uv_stream_s*, long, uv_buf_t const*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x14C7891: uv__read (stream.c:1221)
==28747==    by 0x14C7F37: uv__stream_io (stream.c:1287)
==28747==    by 0x14CDF87: uv__io_poll (linux-core.c:382)
==28747==    by 0x14BD4FB: uv_run (core.c:352)
==28747==
==28747== 168 bytes in 7 blocks are possibly lost in loss record 606 of 681
==28747==    at 0x4C2DACE: malloc (vg_replace_malloc.c:298)
==28747==    by 0x4C2FC81: realloc (vg_replace_malloc.c:785)
==28747==    by 0x12A4FFB: node::http2::Nghttp2Session::OnDataChunkReceived(nghttp2_session*, unsigned char, int, unsigned char const*, unsigned long, void*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x1339869: nghttp2_session_mem_recv (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12A8C34: node::http2::Http2Session::OnStreamReadImpl(long, uv_buf_t const*, uv_handle_type, void*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12E3F3D: node::StreamWrap::OnRead(uv_stream_s*, long, uv_buf_t const*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x14C7891: uv__read (stream.c:1221)
==28747==    by 0x14C7F37: uv__stream_io (stream.c:1287)
==28747==    by 0x14CDF87: uv__io_poll (linux-core.c:382)
==28747==    by 0x14BD4FB: uv_run (core.c:352)
==28747==    by 0x1276262: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x126FA1E: node::Start(int, char**) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==
==28747== 224 bytes in 1 blocks are definitely lost in loss record 614 of 681
==28747==    at 0x4C2E8D9: operator new[](unsigned long) (vg_replace_malloc.c:423)
==28747==    by 0x1299169: node::GetStatValues(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x887898: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90C5B9: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90CEFD: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0xC94D918437C: ???
==28747==    by 0xC94D9328D43: ???
==28747==    by 0xC94D918579A: ???
==28747==    by 0xC94D9268766: ???
==28747==    by 0xC94D923AFFB: ???
==28747==    by 0xC94D9307A26: ???
==28747==    by 0xC94D9324761: ???
==28747==
==28747== 232 bytes in 1 blocks are possibly lost in loss record 615 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x12D910E: node::(anonymous namespace)::SignalWrap::New(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x887898: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90BBAB: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90CF6B: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0xC94D918437C: ???
==28747==    by 0xC94D92376BC: ???
==28747==    by 0xC94D931F89D: ???
==28747==    by 0xC94D931F482: ???
==28747==    by 0xC94D931EFF3: ???
==28747==    by 0xC94D918579A: ???
==28747==    by 0xC94D931B659: ???
==28747==
==28747== 232 bytes in 1 blocks are possibly lost in loss record 616 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x12E9ACE: node::(anonymous namespace)::TimerWrap::New(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x887898: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90BBAB: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90CF6B: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0xC94D918437C: ???
==28747==    by 0xC94D92376BC: ???
==28747==    by 0xC94D939FB67: ???
==28747==    by 0xC94D918536F: ???
==28747==    by 0xC94D939F79F: ???
==28747==    by 0xC94D9388027: ???
==28747==    by 0xC94D9387CAF: ???
==28747==
==28747== 232 bytes in 1 blocks are possibly lost in loss record 617 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x12E9ACE: node::(anonymous namespace)::TimerWrap::New(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x887898: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90BBAB: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90CF6B: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0xC94D918437C: ???
==28747==    by 0xC94D92376BC: ???
==28747==    by 0xC94D93CEA9E: ???
==28747==    by 0xC94D93C159A: ???
==28747==    by 0xC94D93AEC49: ???
==28747==    by 0xC94D93AE1B3: ???
==28747==    by 0xC94D918579A: ???
==28747==
==28747== 288 bytes in 1 blocks are possibly lost in loss record 624 of 681
==28747==    at 0x4C2FA40: calloc (vg_replace_malloc.c:711)
==28747==    by 0x4013B5A: allocate_dtv (dl-tls.c:322)
==28747==    by 0x4013B5A: _dl_allocate_tls (dl-tls.c:539)
==28747==    by 0x5AF6289: allocate_stack (allocatestack.c:586)
==28747==    by 0x5AF6289: pthread_create@@GLIBC_2.2.5 (pthread_create.c:539)
==28747==    by 0x12FBE3B: node::inspector::Agent::Start(v8::Platform*, char const*, node::DebugOptions const&) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12760F9: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x126FA1E: node::Start(int, char**) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x5D2C3F0: (below main) (libc-start.c:291)
==28747==
==28747== 496 bytes in 1 blocks are possibly lost in loss record 632 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x12EDBB8: node::TTYWrap::New(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x887898: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90BBAB: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90CF6B: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0xC94D918437C: ???
==28747==    by 0xC94D92376BC: ???
==28747==    by 0xC94D9357762: ???
==28747==    by 0xC94D918536F: ???
==28747==    by 0xC94D9356637: ???
==28747==    by 0xC94D9356175: ???
==28747==    by 0xC94D9239ED8: ???
==28747==
==28747== 496 bytes in 1 blocks are possibly lost in loss record 633 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x12EDBB8: node::TTYWrap::New(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x887898: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90BBAB: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90CF6B: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0xC94D918437C: ???
==28747==    by 0xC94D92376BC: ???
==28747==    by 0xC94D9357762: ???
==28747==    by 0xC94D918536F: ???
==28747==    by 0xC94D9356637: ???
==28747==    by 0xC94D935C075: ???
==28747==    by 0xC94D9239ED8: ???
==28747==
==28747== 74,371 (128 direct, 74,243 indirect) bytes in 1 blocks are definitely lost in loss record 677 of 681
==28747==    at 0x4C2DACE: malloc (vg_replace_malloc.c:298)
==28747==    by 0x4C2FC81: realloc (vg_replace_malloc.c:785)
==28747==    by 0x14AEA35: config_nameserver (ares_init.c:1674)
==28747==    by 0x14AEA35: init_by_resolv_conf (ares_init.c:1282)
==28747==    by 0x14AEA35: ares_init_options.part.4 (ares_init.c:206)
==28747==    by 0x1253E0D: node::cares_wrap::(anonymous namespace)::SetupCaresChannel(node::Environment*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x1255F71: node::cares_wrap::(anonymous namespace)::Initialize(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x1269658: node::Binding(v8::FunctionCallbackInfo<v8::Value> const&) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x887898: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90C5B9: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x90CEFD: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0xC94D918437C: ???
==28747==    by 0xC94D934E912: ???
==28747==    by 0xC94D918579A: ???
==28747==
==28747== 508,639 bytes in 43 blocks are possibly lost in loss record 678 of 681
==28747==    at 0x4C2E8D9: operator new[](unsigned long) (vg_replace_malloc.c:423)
==28747==    by 0x12A4FA2: node::http2::Nghttp2Session::OnDataChunkReceived(nghttp2_session*, unsigned char, int, unsigned char const*, unsigned long, void*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x1339869: nghttp2_session_mem_recv (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12A8C34: node::http2::Http2Session::OnStreamReadImpl(long, uv_buf_t const*, uv_handle_type, void*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12E3F3D: node::StreamWrap::OnRead(uv_stream_s*, long, uv_buf_t const*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x14C7891: uv__read (stream.c:1221)
==28747==    by 0x14C7F37: uv__stream_io (stream.c:1287)
==28747==    by 0x14CDF87: uv__io_poll (linux-core.c:382)
==28747==    by 0x14BD4FB: uv_run (core.c:352)
==28747==    by 0x1276262: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x126FA1E: node::Start(int, char**) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x5D2C3F0: (below main) (libc-start.c:291)
==28747==
==28747== 4,182,082 (1,182,656 direct, 2,999,426 indirect) bytes in 36,958 blocks are definitely lost in loss record 681 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x1287C64: node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12A5FEE: node::http2::Http2Session::OnDataChunk(node::http2::Nghttp2Stream*, node::http2::nghttp2_data_chunk_t*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12A52D4: node::http2::Nghttp2Session::OnFrameReceive(nghttp2_session*, nghttp2_frame const*, void*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x133493C: nghttp2_session_on_data_received (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x1338596: nghttp2_session_mem_recv (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12A8C34: node::http2::Http2Session::OnStreamReadImpl(long, uv_buf_t const*, uv_handle_type, void*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12E3F3D: node::StreamWrap::OnRead(uv_stream_s*, long, uv_buf_t const*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x14C7891: uv__read (stream.c:1221)
==28747==    by 0x14C7F37: uv__stream_io (stream.c:1287)
==28747==    by 0x14CDF87: uv__io_poll (linux-core.c:382)
==28747==    by 0x14BD4FB: uv_run (core.c:352)
==28747==
==28747== LEAK SUMMARY:
==28747==    definitely lost: 1,183,208 bytes in 36,965 blocks
==28747==    indirectly lost: 3,073,669 bytes in 73,873 blocks
==28747==      possibly lost: 510,879 bytes in 59 blocks
==28747==    still reachable: 168,717 bytes in 4,423 blocks
==28747==                       of which reachable via heuristic:
==28747==                         newarray           : 1,648 bytes in 1 blocks
==28747==         suppressed: 0 bytes in 0 blocks
==28747== Reachable blocks (those to which a pointer was found) are not shown.
==28747== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==28747==
==28747== For counts of detected and suppressed errors, rerun with: -v
==28747== ERROR SUMMARY: 17 errors from 17 contexts (suppressed: 0 from 0)
```

</details>

Note the section:

```
==28747== 4,182,082 (1,182,656 direct, 2,999,426 indirect) bytes in 36,958 blocks are definitely lost in loss record 681 of 681
==28747==    at 0x4C2E1EC: operator new(unsigned long) (vg_replace_malloc.c:334)
==28747==    by 0x1287C64: node::Buffer::New(v8::Isolate*, char*, unsigned long, void (*)(char*, void*), void*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12A5FEE: node::http2::Http2Session::OnDataChunk(node::http2::Nghttp2Stream*, node::http2::nghttp2_data_chunk_t*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x12A52D4: node::http2::Nghttp2Session::OnFrameReceive(nghttp2_session*, nghttp2_frame const*, void*) (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x133493C: nghttp2_session_on_data_received (in /home/james/node/http2-jasnell/out/Release/node)
==28747==    by 0x1338596: nghttp2_session_mem_recv (in /home/james/node/http2-jasnell/out/Release/node)
...
```

Here we have Buffer allocations that are not being gc'd before the process exits. This memory is going to be retained until gc occurs.

Running the same test with calls to `gc()` scattered throughout yields significantly better results (only 1,800 bytes "definitely lost" due to non gc'd memory when the test exits.

@mcollina ... as you can see from the report, there are a number of other areas where memory is being lost. At some point we should track those down

**Review by mcollina — APPROVED** [review]
LGTM

**Comment by jasnell** [comment]
Landed!

**Comment by sebdeckers** [comment]
@jasnell Of course, LGTM! (I don't really have reviewer access though 😜)

Really interesting to learn about this stuff. Will try to contribute more on this front. Thanks for sharing!

**Pull request closed without merging**
