### PR TITLE
http2: add priority advisement event

### PR DESCRIPTION
**Pull request by jasnell**
Trigger a 'priority' event on the session, stream, and server when a priority frame is received.

Refs: https://github.com/nodejs/http2/issues/69

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-guidelines)

##### Affected core subsystem(s)

http2

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Shouldn't priority have a callback attached?

**Comment by jasnell** [comment]
attached where? not sure I follow

**Comment by mcollina** [comment]
Sorry, I meant req.priority(obj, callback)

**Comment by jasnell** [comment]
No, at least not right now. Calling `req.priority()` tells nghttp to send a priority frame, which is done on the next tick of the event loop when nghttp is prompted to send whatever frames it has queued up. Currently, that's a fire and forget mechanism. We can make it more intelligent or introduce a callback later if need arises, but for the time being, there does not appear to be a need for it.

**Comment by mcollina** [comment]
@jasnell can you add a comment on this? From a consistency perspective, a synchronous API that does something on the next event loop tick is not consistent. I agree that there is no need for having a callback right now, but we have to document it properly.

**Review by mcollina — APPROVED** [review]
LGTM

**Comment by yosuke-furukawa** [comment]
LGTM

**Comment by jasnell** [comment]
Yes, I will add a comment... however, it's the same situation for most of the operations that cause nghttp to queue data up to be sent. Specifically, the methods either queue things up in nghttp's own internal frame buffer or in our link lists... then on the next tick, nghttp is prompted to begin sending the buffered data, which drains it's own internal buffer and our linked list. The data writes are the only thing that currently have callbacks attached to them. I'll make a note to look into how feasible it would be to add callbacks to everything.

**Comment by mcollina** [comment]
@jasnell most of the other APIs are behind streams interactions, which makes them easy to understand from a user point of view. At least, they know they will be asynchronous. `priority` on the other end it is async, but it looks sync. I think we can move forward here, just add a comment so that we know it is something to document well.

**Comment by jasnell** [comment]
Landed with note added

**Pull request closed without merging**
