### PR TITLE
http2: CONNECT method support, test and docs

### PR DESCRIPTION
**Pull request by jasnell**
Support for the CONNECT method, add test to make sure it works

##### Checklist
- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)
http2

### CODE REVIEW

**Review by sebdeckers — APPROVED** [review]
LGTM 👍 (Only read the code. Didn't try running it yet. Funny how the test is basically the entire  implementation. 😝)

**Review by mcollina — APPROVED** [review]
LGTM with CI green

**Comment by jasnell** [comment]
CI: https://ci.nodejs.org/job/node-test-pull-request/8893/

**Comment by jasnell** [comment]
CI failures are unrelated.

**Comment by jasnell** [comment]
Landed

**Pull request closed without merging**
