### PR TITLE
Enable auto window size updates

### PR DESCRIPTION
**Pull request by kjin**
This is an attempt to address #55, as manually specifying the amount of data consumed seem to cause a receiver not to emit WINDOW_UPDATE frames in some cases.

It seemed like disabling auto window updates was an intentional decision, though, so I'd be interested in knowing why this was the case.

### CODE REVIEW

**Comment by jasnell** [comment]
It was intentionally done to give us a bit of flexibility while prototyping, benchmarking and determining if a manual strategy would be more efficient. Given the experience so far, however, I think allowing nghttp to handle it automatically is the better strategy.

**Review by jasnell — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
LGTM

**Comment by kjin** [comment]
@jasnell Ok, thanks for the explanation!

**Comment by jasnell** [comment]
Landed

**Pull request closed without merging**
