### PR TITLE
Round 11

### PR DESCRIPTION
**Pull request by jasnell**
beginning of round 11, starting with some API refinement

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
I'm actually 👎  on this change, if it is possible.

In the rest of core we have:

```js
const sock = net.connect()
```

while here we will have:

```js
h2.connect(url, function (err, client) {

})
```

I think we should strive to implement the delayed open pattern in h2, it will simplify usage greatly. However, if it is unfeasible, we would have to implement an agent-like behavior on top.

**Comment by jasnell** [comment]
Understood. This is incremental while I work out the requirements on a few other bits. The delayed open pattern is going to be a bit of a larger internal change so I'm pushing it off slightly

**Comment by mcollina** [comment]
Good job! I like having just a single `connect()`.

**Comment by jasnell** [comment]
I should have another round of updates on this later today

**Comment by mcollina** [comment]
@jasnell that execution bit looks really bad on the files.

**Comment by jasnell** [comment]
Ugh. I keep forgetting about that. Will switch it up :)

**Comment by jasnell** [comment]
Going to get this landed in master, then open a PR that updates with the current upstream master

**Comment by jasnell** [comment]
Landed

**Pull request closed without merging**
