### PR TITLE
http2: enable the compatibility mode

### PR DESCRIPTION
**Pull request by mcollina**
cc @jasnell 

There are a couple of functions I could not find, do you still have the code around?

I need to still work on this anyway.

### CODE REVIEW

**Comment by mcollina** [comment]
@jasnell from my tests the performance of this is almost on par with Http2Stream.
It's far from complete and it needs more testing to be 100% compliant with the Stream API.

**Comment by jasnell** [comment]
excellent. I do have another update pending. Are you basing this off master or my round 10 pr?

**Comment by jasnell** [comment]
any code removed should be either in the compat or util js files commented out.

**Comment by mcollina** [comment]
this is on master, but those missing things are not to be found:

`isPseudoHeader`
`isIllegalConnectionSpecificHeader`
`llistToHeaders`

**Comment by mcollina** [comment]
I can rebase on top of round10 before landing.

**Comment by jasnell** [comment]
Each of those methods is here: https://github.com/nodejs/http2/blob/master/lib/internal/http2/util.js

You likely don't need to worry about `llistToHeaders` in the compat layer. 

There is a fix I still need to do here to make sure that `:' prefixed headers appear first in the list passed down to the binding layer.

**Comment by mcollina** [comment]
@jasnell those method does not work with the current code, as the headers in `stream.respond()` are an object, while they produce an array.

**Comment by jasnell** [comment]
Yeah, the methods have changed a bit. I'll work up an example of what's needed on the input shortly

**Comment by mcollina** [comment]
> Yeah, the methods have changed a bit. I'll work up an example of what's needed on the input shortly

@jasnell ping :)

**Comment by jasnell** [comment]
oh sorry, lol..

Here is a minimal server:

```js
'use strict';

const http2 = require('http2');
const util = require('util');
const constants = http2.constants;

const options = {};

const server = http2.createServer(options, (stream, headers) => {
  stream.respond({
    [constants.HTTP2_HEADER_STATUS]: 200,
    'foo': 'bar'
  });
  stream.end('ok');
});

server.listen(8000);
```
The first argument to the `stream.respond()` method is an object that will be translated into the appropriate array structure internally.

**Comment by mcollina** [comment]
this is good to go now, minus #40 to be solved.

**Comment by mcollina** [comment]
@jasnell this is ready to go, may I merge?

**Review by jasnell — APPROVED** [review]

**Comment by mcollina** [comment]
I've fixed a broken test and linted everything as well, hope you don't mind.

**Comment by jasnell** [comment]
Woot! Lgtm

**Pull request merged**
