### PR TITLE
http2: initial benchmarks

### PR DESCRIPTION
**Pull request by jasnell**
To run benchmarks ...

```
$ ./node benchmarks/http2/simple.js benchmarker=h2load
```

##### Checklist
- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] tests and/or benchmarks are included
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
You should update the benchmark docs, saying that they need nghttp2/h2load installed as well.

**Comment by jasnell** [comment]
Added!

**Comment by mcollina** [comment]
LGTM
Il giorno ven 14 lug 2017 alle 19:01 James M Snell <notifications@github.com>
ha scritto:

**Comment by jasnell** [comment]
Landed!

**Pull request closed without merging**
