### PR TITLE
deps: initial checkin of nghttp2 lib 1.15.0

### PR DESCRIPTION
**Pull request by jasnell**
Initial checkin of the nghttp2 lib to get this party started.
@nodejs/http2 @nodejs/collaborators

TODO: Need to update the LICENSE file

### CODE REVIEW

**Comment by doug-wade** [comment]
🚀✨👍

**Comment by mcollina** [comment]
LGTM.

**Comment by indutny** [comment]
LGTM

**Review by indutny — APPROVED** [review]

**Comment by jasnell** [comment]
Landed in 2ba6a2d

**Pull request closed without merging**
