### PR TITLE
Second round of implementation upates

### PR DESCRIPTION
**Pull request by jasnell**
A second round of implementation updates... this is an ongoing work in progress.
This update represents a significant ongoing refactoring and filling out of the implementation and API detail.

### CODE REVIEW

**Comment by jasnell** [comment]
Will be getting this landed shortly...

**Comment by AndrewBarba** [comment]
@jasnell Since this is an addition to the `http` lib is there a chance we see this released in a v6 update instead of waiting for v7 or later? Not sure how others are handling versions but our team is maintaining a strict LTS policy so we wouldn't be able to use this if it doesn't land until the next LTS.

Edit: I mean http2 as a whole. Sorry if that wasn't clear or if this PR is not the place to ask about that.

**Comment by jasnell** [comment]
This is going to be a long process. It would be introduced first as an
experimental feature if the ctc decides to accept it. It should be a
semver-minor update so backporting should be possible but it's going to be
quite a while before this is ready for that

**Comment by jasnell** [comment]
This pr is merged. Closing. Starting round 3

**Pull request closed without merging**
